---
title: "hps_sa"
author: "Uriel Lomelí"
date: "5/8/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE, include=FALSE}
pacman::p_load(tidyverse, readxl, janitor, ggthemes, ggsci, magrittr, wesanderson, showtext, ggrepel, tidyr, forcats, questionr, survey, sysfonts, hrbrthemes, expss, gtsummary, gt)
```

```{r load, message=FALSE, include=FALSE}
# hps - this need to change to your directory
week27 <- read_csv("C:/Users/Uriel/Downloads/pulse2021_puf_27.csv")
# sa survey - this need to change to your directory
load(file = "~/GitHub/saetus/data_recode.RData")
```

```{r theme, include=FALSE, message=FALSE, warning=FALSE}
sysfonts::font_add_google(name = 'Lato', family = "foo")
showtext::showtext_auto()

# themeu <- theme(legend.position = "bottom", 
#                 legend.text = element_text(size = 15, color = "gray40"), 
#                 legend.key.size = unit(.5, "cm"),
#                 panel.background = element_rect(colour = "black"),
#                 plot.title = element_text(face = "bold", size = 30, hjust = .5, vjust = .5, lineheight = .5), 
#                 plot.caption = element_text(size = 15),
#                 plot.subtitle = element_text(colour = "gray50", face = "bold", size = 22, lineheight = .5, hjust = .5, vjust = .5),
#                 axis.text = element_text(size = 20), 
#                 text = element_text(family = "foo"))
# 
# themeuf <- theme(legend.position = "top", 
#                  legend.text = element_text(size = 25, color = "gray10"), 
#                  legend.key.size = grid::unit(.5, "cm"), 
#                  legend.title = element_text(color = "gray25", face = "bold", size = 20), 
#                  panel.background = element_rect(colour = "black"),
#                  plot.title = element_text(face = "bold", size = 32, hjust = .5, vjust = .5, lineheight = .5), 
#                  plot.caption = element_text(size = 19),
#                  plot.subtitle = element_text(colour = "gray30", face = "bold", size = 26, lineheight = .5, hjust = .5, vjust = .5),
#                  axis.text = element_text(size = 27, color = "gray10", face = "bold"),
#                  strip.text = element_text(size = 25), 
#                  axis.title.x = element_text(color = "gray10", size = 25), 
#                  axis.ticks.y = element_blank(),
#                  panel.grid.major.x = element_blank(),
#                  panel.grid.minor.x = element_blank(),
#                  panel.grid.major.y = element_line(colour = "grey70", linetype = "dotted"),
#                  plot.tag = element_text(size = 30),
#                  text = element_text(family = "foo"))
```

```{r function, include=FALSE}
week27 <- as.data.frame(week27)

# same national numbers
week27 %>%
  filter(RECVDVACC==1)%>%
  dplyr::count(estate = EST_ST, wt = PWEIGHT)

# simply function
func1 <- function(week) {
  
  week <- week %>%
    janitor::clean_names() # To lower case and underscore instead of spaces
  
  return(week)
}

week27 <- func1(week = week27)
```

```{r recode, include=FALSE}
# san antionio survey
data <- data %>% 
  mutate(race_eth2 = case_when(race_eth %in% "NH-White" ~ "Non-Hispanic White",
                               race_eth %in% "Hispanic" ~ "Hispanic",
                               race_eth %in% "NH-Black" ~ "Non-Hispanic Black",
                               race_eth %in% "NH-Asian" ~ "Non-Hispanic Asian",
                               race_eth %in% c("NH-AIAN", "NH-NHPI", "NH-Other") ~ "Non-Hispanic Other"),
         race_eth3 = case_when(race_eth %in% "NH-White" ~ "Non-Hispanic White",
                               race_eth %in% "Hispanic" ~ "Hispanic",
                               race_eth %in% c("NH-Black", "NH-Asian", "NH-AIAN", "NH-NHPI", "NH-Other") ~ "Non-Hispanic Other"))

data$race_eth <- ordered(data$race_eth, levels = c("Hispanic", "NH-White", "NH-Black", "NH-Asian", "NH-AIAN", "NH-NHPI", "NH-Other"))
data$race_eth2 <- ordered(data$race_eth2, 
                          levels = c("Hispanic", "Non-Hispanic White", "Non-Hispanic Black", "Non-Hispanic Asian","Non-Hispanic Other"))
data$race_eth3 <- ordered(data$race_eth3, levels = c("Hispanic", "Non-Hispanic White", "Non-Hispanic Other"))
data$health <- ordered(data$health, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"))

# household pulse survey
hps <- week27 %>%
  mutate(hispanic = ifelse(rhispanic == 2, "Hispanic", "Non-Hispanic"), 
         race = case_when(rrace %in% 1 ~ "Non-Hispanic White",
                          rrace %in% 2 ~ "Non-Hispanic Black",
                          rrace %in% 3 ~ "Non-Hispanic Asian",
                          rrace %in% 4 ~ "Non-Hispanic Any other race"),
         gender = ifelse(egender == 1, "Male", "Female"),
         education = case_when(eeduc %in% 1:2 ~ "Less or some than HS",
                               eeduc %in% 3 ~ "HS graduate",
                               eeduc %in% 4:5 ~ "Some college", # or Associate's degree
                               eeduc %in% 6 ~ "Bachelor's degree",
                               eeduc %in% 7 ~ "Graduate degree"),
         marital = case_when(ms %in% 1 ~ "Married",
                             ms %in% 2:4 ~"Separate", # Widow, divorced or separated
                             ms %in% 5 ~ "Single"))

hps$race_eth <- interaction(hps$race, hps$hispanic)

hps$race_eth2 <- ifelse(str_sub(as.character(hps$race_eth), start = -12) == "Non-Hispanic", as.character(hps$race_eth),"Hispanic")

hps$race <- ordered(hps$race, 
                    levels = c("Non-Hispanic White", "Non-Hispanic Black", "Non-Hispanic Asian", "Non-Hispanic Any other race"))

hps$gender <- ordered(hps$gender, levels = c("Male", "Female"))

hps$education <- ordered(hps$education, 
                          levels = c("Less or some than HS", "HS graduate", "Some college", "Bachelor's degree", "Graduate degree"))

hps$marital <- ordered(hps$marital, levels = c("Married", "Separate", "Single"))

hps <- hps %>%
  mutate(work.loss = if_else(wrkloss == 1, "Yes", "No"),
         metro = case_when(est_msa %in% '35620' ~ "New York-Newark-Jersey City",
                           est_msa %in% '31080' ~ "Los Angeles-Long Beach-Anaheim",
                           est_msa %in% '16980' ~ "Chicago-Naperville-Elgin",
                           est_msa %in% '19100' ~ "Dallas-Fort Worth-Arlington",
                           est_msa %in% '26420' ~ "Houston-The Woodlands-Sugar Land",
                           est_msa %in% '47900' ~ "Washington-Arlington-Alexandria",
                           est_msa %in% '33100' ~ "Miami-Fort Lauderdale-Pompano Beach",
                           est_msa %in% '37980' ~ "Philadelphia-Camden-Wilmington", 
                           est_msa %in% '12060' ~ "Atlanta-Sandy Springs-Alpharetta", 
                           est_msa %in% '38060' ~ "Phoenix-Mesa-Chandler", 
                           est_msa %in% '14460' ~ "Boston-Cambridge-Newton", 
                           est_msa %in% '41860' ~ "San Francisco-Oakland-Berkeley",
                           est_msa %in% '40140' ~ "Riverside-San Bernardino-Ontario",
                           est_msa %in% '19820' ~ "Detroit-Warren-Dearborn",
                           est_msa %in% '42660' ~ "Seattle-Tacoma-Bellevue"),
         mh_anxious = case_when(anxious %in% 1 ~ "Not at all",
                                anxious %in% 2 ~ "Several days",
                                anxious %in% 3 ~ "More than half the days",
                                anxious %in% 4 ~ "Nearly every day"),
         mh_worry = case_when(worry %in% 1 ~ "Not at all",
                              worry %in% 2 ~ "Several days",
                              worry %in% 3 ~ "More than half the days",
                              worry %in% 4 ~ "Nearly every day"),
         mh_interest = case_when(interest %in% 1 ~ "Not at all",
                                 interest %in% 2 ~ "Several days",
                                 interest %in% 3 ~ "More than half the days",
                                 interest %in% 4 ~ "Nearly every day"),
         mh_down = case_when(down %in% 1 ~ "Not at all",
                             down %in% 2 ~ "Several days",
                             down %in% 3 ~ "More than half the days",
                             down %in% 4 ~ "Nearly every day"),
         age = 2020 - tbirth_year,
         ageg = case_when(age %in% 18:24 ~ "18 to 24",
                          age %in% 25:34 ~ "25 to 34",
                          age %in% 35:44 ~ "35 to 44",
                          age %in% 45:54 ~ "45 to 54",
                          age %in% 55:64 ~ "55 to 64",
                          age %in% 65:74 ~ "65 to 74",
                          age %in% 75:100 ~ "75 or more"))

hps$ageg <- ordered(hps$ageg, levels = c("18 to 24", "25 to 34", "35 to 44", "45 to 54", "55 to 64", "65 to 74", "75 or more"))

hps$state <- dplyr::recode(hps$est_st, 
                    '01'='Alabama', '02'='Alaska', '04'='Arizona', '05'='Arkansas', '06'='California',
                    '08'='Colorado', '09'='Connecticut', '10'='Delaware', '11'='District of Columbia', '12'='Florida',
                    '13'='Georgia', '15'='Hawaii', '16'='Idaho', '17'='Illinois', '18'='Indiana', '19'='Iowa', '20'='Kansas',
                    '21'='Kentucky', '22'='Louisiana', '23'='Maine', '24'='Maryland', '25'='Massachusetts', '26'='Michigan',
                    '27'='Minnesota', '28'='Mississippi', '29'='Missouri', '30'='Montana', '31'='Nebraska', '32'='Nevada',
                    '33'='New Hampshire', '34'='New Jersey', '35'='New Mexico', '36'='New York', '37'='North Carolina',
                    '38'='North Dakota', '39'='Ohio', '40'='Oklahoma', '41'='Oregon', '42'='Pennsylvania', '44'='Rhode Island',
                    '45'='South Carolina', '46'='South Dakota', '47'='Tennessee', '48'='Texas', '49'='Utah', '50'='Vermont',
                    '51'='Virginia', '53'='Washington', '54'='West Virginia', '55'='Wisconsin', '56'='Wyoming')
```

```{r subset, include=FALSE}
# subset hps
hps <- hps %>%
   select(scram, 5:7, hispanic:state)

hps <- hps %>% 
  mutate(mh_anxious = case_when(mh_anxious %in% "Not at all" ~ 0,
                                mh_anxious %in% "Several days" ~ 1,
                                mh_anxious %in% "More than half the days" ~ 2,
                                mh_anxious %in% "Nearly every day" ~ 3),
         mh_worry = case_when(mh_worry %in% "Not at all" ~ 0,
                              mh_worry %in% "Several days" ~ 1,
                              mh_worry %in% "More than half the days" ~ 2,
                              mh_worry %in% "Nearly every day" ~ 3),
         mh_interest = case_when(mh_interest %in% "Not at all" ~ 0,
                                 mh_interest %in% "Several days" ~ 1,
                                 mh_interest %in% "More than half the days" ~ 2,
                                 mh_interest %in% "Nearly every day" ~ 3),
         mh_down = case_when(mh_down %in% "Not at all" ~ 0,
                             mh_down %in% "Several days" ~ 1,
                             mh_down %in% "More than half the days" ~ 2,
                             mh_down %in% "Nearly every day" ~ 3),
         mh_gad2 = mh_anxious + mh_worry,
         mh_phq2 = mh_interest + mh_down,
         gad2 = if_else(mh_gad2 >= 3, "Generalized Anxiety", "No GA"),
         phq2 = if_else(mh_phq2 >= 3, "Depressive Disorder", "No DD"))
  
# subset survey and change name to work mental health related variables
data <- data %>% 
   select(1, 2, 95:99, 128, 129, 132, 133, 188:197)

sas <- data %>%
  mutate(mh_anx = case_when(mental_health_anxious %in% "Not at all" ~ 0,
                            mental_health_anxious %in% "Several days" ~ 1,
                            mental_health_anxious %in% "More than half the days" ~ 2,
                            mental_health_anxious %in% "Nearly every day" ~ 3),
         mh_worry = case_when(mental_health_worry %in% "Not at all" ~ 0,
                            mental_health_worry %in% "Several days" ~ 1,
                            mental_health_worry %in% "More than half the days" ~ 2,
                            mental_health_worry %in% "Nearly every day" ~ 3),
         mh_interest = case_when(mental_health_interest %in% "Not at all" ~ 0,
                            mental_health_interest %in% "Several days" ~ 1,
                            mental_health_interest %in% "More than half the days" ~ 2,
                            mental_health_interest %in% "Nearly every day" ~ 3),
         mh_down = case_when(mental_health_down %in% "Not at all" ~ 0,
                            mental_health_down %in% "Several days" ~ 1,
                            mental_health_down %in% "More than half the days" ~ 2,
                            mental_health_down %in% "Nearly every day" ~ 3),
         mh_gad2 = mh_anx + mh_worry,
         mh_phq2 = mh_interest + mh_down,
         gad2 = if_else(mh_gad2 >= 3, "Generalized Anxiety", "No GA"),
         phq2 = if_else(mh_phq2 >= 3, "Depressive Disorder", "No DD"))

sas <- sas %>%
  mutate_at(vars(emp_status), ~if_else(. %in% c("Work for pay at a job","Temporarily absent from job"), "employed",
                                    if_else(. %in% c("Layoff from a job","Actively looking for a job"), "unemployed",
                                            if_else(. %in% c("Retired", "Unable to work"), "retired", "NA"))))

save(sas, file = "~/GitHub/saetus/sas.RData")
#load(file = "~/GitHub/saetus/sas.RData")
```

```{r unemp_plot, warning=FALSE, message=FALSE, include=FALSE}
total <- sas %>%
  filter(emp_status != "NA", !is.na(gad2)) %>%
  group_by(zipcode, race_eth3, gad2) %>%
  dplyr::summarize(n = n())

unemployed <- sas %>%
  filter(emp_status == "unemployed", !is.na(gad2)) %>%
  group_by(zipcode, race_eth3, gad2) %>%
  dplyr::summarize(unemployed_n = n())

unemployed <- data.frame(unemployed)

colnames(unemployed) <- c("zipcode","race_eth3", "gad", "unemployed_n")

unemployed <- unemployed[with(unemployed, order(zipcode, race_eth3)),] 

unemployed_pct <- data.frame(total[,"zipcode"], total[,"race_eth3"], total[, "gad2"], total[,"n"], unemployed[,"unemployed_n"])

colnames(unemployed_pct) <- c("zipcode","race_eth3","gad", "n","unemployed_n")

unemployed_pct$unemployed_n <- as.numeric(unemployed_pct$unemployed_n)

unemployed_pct <- unemployed_pct %>%
        mutate(pct = unemployed_n/n,
               lbl = scales::percent(pct, accuracy = 0.1))

unemployed_pct %>%
  ggplot(aes(x = pct, y = reorder(race_eth3, -pct), color = zipcode)) + 
  #geom_errorbar(aes(xmin = lower, xmax = upper), show.legend = F, width = 0.1) +
  geom_point(aes(size = n, shape = factor(gad))) +
  geom_text_repel(aes(label = lbl), size = 7, color = "gray10", segment.alpha = 0, family = "foo", nudge_y = .3, nudge_x = .01) +
  scale_x_continuous(limits = c(0, .60), breaks = seq(0, 1, .15), label = scales::percent) +
  scale_color_manual(values = wes_palette("Darjeeling2", n = 3)) +
  guides(color = guide_legend(label.position = "left", label.vjust = 0.5, label.hjust = 1, override.aes = list(size = 5)), 
         size = F) +
  labs(y = NULL, x = NULL, color = NULL, 
       subtitle = "A) Unemployment by race and ethnicity") +
  theme_classic() +
  theme(legend.position = "bottom") 

#ggsave(filename = "figure_2.png", plot = last_plot(), path = "~/GitHub/saetus/", width = 6, height = 4.5, units = "in", dpi = "print")
```

```{r gad, message=FALSE, include=FALSE}
sas %>%
  filter(!is.na(gad2)) %>% 
  group_by(zipcode, gad2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = zipcode)) + 
  geom_point(aes(color = gad2, size = n)) +
  geom_text(aes(label = lbl), size = 5, color = "gray30", position = position_dodge(width = .9), vjust = -.7, family = "foo") +
  scale_x_continuous(limits = c(0.3, .7), breaks = seq(0, 1, .1), label = scales::percent) +
  scale_color_jama() +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = "GAD-2", size = NULL,
       title = str_wrap("Generalized Anxiety Disorder 2-item by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  theme_classic() + theme(legend.position = "top")

hps %>%
  filter(!is.na(gad2), !is.na(metro)) %>% 
  group_by(metro, gad2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = metro)) + 
  geom_point(aes(color = gad2, size = n)) +
  geom_text(aes(label = lbl), size = 3, color = "gray30", position = position_dodge(width = .9), vjust = -.7, family = "foo") +
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, .1), label = scales::percent) +
  scale_color_jama() +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = "GAD-2", size = NULL,
       title = str_wrap("Generalized Anxiety Disorder 2-item by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  theme_classic() + theme(legend.position = "top")

sas %>%
  filter(hardships_1 == 1, !is.na(gad2)) %>% 
  group_by(zipcode, gad2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = zipcode)) + 
  geom_point(aes(color = gad2, size = n)) +
  geom_text(aes(label = lbl), size = 5, color = "gray30", position = position_dodge(width = .9), vjust = -.7, family = "foo") +
  scale_x_continuous(limits = c(0.3, .7), breaks = seq(0, 1, .1), label = scales::percent) +
  scale_color_jama() +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = str_wrap("Generalized Anxiety Disorder 2-item by zip code", width = 75), 
       subtitle = str_wrap("Among those who lost their jobs"),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  theme_classic() + theme(legend.position = "top")
```

```{r phq, message=FALSE, include=FALSE}
sas %>%
  filter(!is.na(phq2)) %>% 
  group_by(zipcode, phq2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = zipcode)) + 
  geom_point(aes(color = phq2, size = n)) +
  geom_text(aes(label = lbl), size = 5, color = "gray30", position = position_dodge(width = .9), vjust = -.7, family = "foo") +
  scale_x_continuous(limits = c(0.3, .7), breaks = seq(0, 1, .1), label = scales::percent) +
  scale_color_jama() +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = str_wrap("Patient Health Questionnaire-2 by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  theme_classic() + theme(legend.position = "top")

hps %>%
  filter(!is.na(phq2), !is.na(metro)) %>% 
  group_by(metro, phq2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = metro)) + 
  geom_point(aes(color = phq2, size = n)) +
  geom_text(aes(label = lbl), size = 5, color = "gray30", position = position_dodge(width = .9), vjust = -.7, family = "foo") +
  scale_x_continuous(limits = c(0.1, .9), breaks = seq(0, 1, .1), label = scales::percent) +
  scale_color_jama() +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = str_wrap("Patient Health Questionnaire-2 by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  theme_classic() + theme(legend.position = "top")

sas %>%
  filter(hardships_1 == 1, !is.na(phq2)) %>% 
  group_by(zipcode, phq2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = zipcode)) + 
  geom_point(aes(color = phq2, size = n)) +
  geom_text(aes(label = lbl), size = 5, color = "gray30", position = position_dodge(width = .9), vjust = -.7, family = "foo") +
  scale_x_continuous(limits = c(0.3, .7), breaks = seq(0, 1, .1), label = scales::percent) +
  scale_color_jama() +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = str_wrap("Patient Health Questionnaire-2 by zip code", width = 75), 
       subtitle = str_wrap("Among those who lost their jobs"),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  theme_classic() + theme(legend.position = "top")
```

```{r gad_race_eth, message=FALSE, include=FALSE}
sas %>%
  filter(!is.na(gad2)) %>% 
  group_by(zipcode, gad2, race_eth3) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = reorder(race_eth3, pct))) + 
  geom_point(aes(color = gad2, size = n)) +
  geom_text_repel(aes(label = lbl), size = 4, color = "gray30", family = "foo") +
  scale_x_continuous(limits = c(0, .6), breaks = seq(0, 1, .15), label = scales::percent) +
  scale_color_igv(palette = "alternating") +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = NULL, size = NULL,
       title = str_wrap("Generalized Anxiety Disorder 2-item (GAD-2) by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  facet_grid(~zipcode) +
  theme_classic() + theme(legend.position = "top")

hps %>%
  filter(!is.na(gad2), !is.na(metro)) %>% 
  group_by(metro, gad2, race_eth2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = reorder(metro, pct))) + 
  geom_point(aes(color = gad2, size = n)) +
  geom_text(aes(label = lbl), size = 2, color = "gray30", family = "foo") +
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, .15), label = scales::percent) +
  scale_color_igv(palette = "alternating") +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = NULL, size = NULL,
       title = str_wrap("Generalized Anxiety Disorder 2-item (GAD-2) by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  facet_grid(~race_eth2) +
  theme_classic() + theme(legend.position = "top")

sas %>%
  filter(hardships_1 == 1, !is.na(gad2)) %>% 
  group_by(zipcode, gad2, race_eth3) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = reorder(race_eth3, pct))) + 
  geom_point(aes(color = gad2, size = n)) +
  geom_text_repel(aes(label = lbl), size = 4, color = "gray30", family = "foo") +
  scale_x_continuous(limits = c(0, .6), breaks = seq(0, 1, .15), label = scales::percent) +
  scale_color_igv(palette = "alternating") +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = NULL, size = NULL,
       title = str_wrap("Generalized Anxiety Disorder 2-item by zip code", width = 75), 
       subtitle = str_wrap("Among those who lost their jobs"),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  facet_grid(~zipcode) +
  theme_classic() + theme(legend.position = "top")
```

```{r phq_race_eth, message=FALSE, include=FALSE}
sas %>%
  filter(!is.na(phq2)) %>% 
  group_by(zipcode, phq2, race_eth3) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = reorder(race_eth3, pct))) + 
  geom_point(aes(color = phq2, size = n)) +
  geom_text_repel(aes(label = lbl), size = 4, color = "gray30", family = "foo") +
  scale_x_continuous(limits = c(0, .6), breaks = seq(0, 1, .15), label = scales::percent) +
  scale_color_igv(palette = "alternating") +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = NULL, size = NULL,
       title = str_wrap("Patient Health Questionnaire-2 (PHQ-2) by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  facet_grid(~zipcode) +
  theme_classic() + theme(legend.position = "top")

hps %>%
  filter(!is.na(phq2), !is.na(metro)) %>% 
  group_by(metro, phq2, race_eth2) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = reorder(metro, pct))) + 
  geom_point(aes(color = phq2, size = n)) +
  geom_text(aes(label = lbl), size = 2, color = "gray30", family = "foo") +
  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, .15), label = scales::percent) +
  scale_color_igv(palette = "alternating") +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = NULL, size = NULL,
       title = str_wrap("Patient Health Questionnaire-2 (PHQ-2) by zip code", width = 75),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  facet_grid(~race_eth2) +
  theme_classic() + theme(legend.position = "top")

sas %>%
  filter(hardships_1 == 1, !is.na(phq2)) %>% 
  group_by(zipcode, phq2, race_eth3) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct, accuracy = 0.1)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pct, y = reorder(race_eth3, pct))) + 
  geom_point(aes(color = phq2, size = n)) +
  geom_text_repel(aes(label = lbl), size = 4, color = "gray30", family = "foo") +
  scale_x_continuous(limits = c(0, .6), breaks = seq(0, 1, .15), label = scales::percent) +
  scale_color_igv(palette = "alternating") +
  guides(size = FALSE) +
  labs(y = NULL, x = NULL, color = NULL, size = NULL,
       title = str_wrap("Patient Health Questionnaire-2 (PHQ-2) by zip code", width = 75), 
       subtitle = str_wrap("Among those who lost their jobs"),
       caption = "Source: 2021 San Antonio Energy and Time Use Survey") +
  facet_grid(~zipcode) +
  theme_classic() + theme(legend.position = "top")
```

```{r summary_gad_phq, message=FALSE, warning=FALSE}
set_gtsummary_theme(x = theme_gtsummary_compact())
set_gtsummary_theme(x = theme_gtsummary_journal("jama"))

########### San Antonio #############

# Generalized Anxiety Disorder 2-item (GAD-2)
sas %>% 
  select(2, 3, 8, 10, 13, 17:19, 21, 28) %>% 
  tbl_summary(by = gad2, 
              label = list(zipcode ~ "Zip code",
                           health ~ "Health status",
                           emp_status ~ "Employment status",
                           frontline ~ "Frontline worker",
                           ageg ~ "Age group",
                           gender2 ~ "Gender",
                           marital_st ~ "Marital status",
                           educ ~ "Educational level",
                           race_eth3 ~ "Race and ethnicity")) %>% 
  add_n() %>% 
  add_p() %>% 
  add_overall() %>% 
  modify_header(label ~ "**Variable**") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**GAD-2**") %>%
  modify_caption("**Generalized Anxiety Disorder 2-item (GAD-2)**") %>%
  bold_labels() %>% 
  as_gt() %>%
  gt::tab_source_note(gt::md("*Source: 2021 San Antonio Energy and Time Use Survey*"))

# Patient Health Questionnaire-2 (PHQ-2)
sas %>% 
  select(2, 3, 8, 10, 13, 17:19, 21, 29) %>% 
  tbl_summary(by = phq2, 
              label = list(zipcode ~ "Zip code",
                           health ~ "Health status",
                           emp_status ~ "Employment status",
                           frontline ~ "Frontline worker",
                           ageg ~ "Age group",
                           gender2 ~ "Gender",
                           marital_st ~ "Marital status",
                           educ ~ "Educational level",
                           race_eth3 ~ "Race and ethnicity")) %>% 
  add_n() %>% 
  add_p() %>% 
  add_overall() %>% 
  modify_header(label ~ "**Variable**") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**PHQ-2**") %>%
  modify_caption("**Patient Health Questionnaire-2 (PHQ-2)**") %>%
  bold_labels() %>% 
  as_gt() %>%
  gt::tab_source_note(gt::md("*Source: 2021 San Antonio Energy and Time Use Survey*"))

########### HPS #############

hps$region <- as.factor(hps$region)
hps$gender <- factor(hps$gender, ordered = F)
hps$education <- factor(hps$education, ordered = F)
hps$marital <- factor(hps$marital, ordered = F)
hps$race_eth2 <- factor(hps$race_eth2, ordered = F)
hps$work.loss <- factor(hps$work.loss, ordered = F)
hps$metro <- factor(hps$metro, ordered = F)
hps$ageg <- factor(hps$ageg, ordered = F)
hps$state <- factor(hps$state, ordered = F)

options(survey.lonely.psu = "adjust")

# Generalized Anxiety Disorder 2-item (GAD-2)
hps.tab <- survey::svydesign(ids = ~1, weights = ~pweight, data = hps, strata = NULL) %>%
  tbl_svysummary(by = "gad2", 
                 include = c(gender, education, marital, race_eth2, work.loss, metro, ageg, state, gad2), 
                 percent = "column",
                 label = list(metro ~ "Metropolitan area",
                              state ~ "State",
                              ageg ~ "Age group",
                              gender ~ "Gender",
                              marital ~ "Marital status",
                              education ~ "Educational level",
                              race_eth2 ~ "Race and ethnicity")) %>% 
  add_n() %>% 
  add_p() %>% 
  add_overall() %>% 
  modify_header(label ~ "**Variable**") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**GAD-2**") %>%
  modify_caption("**Generalized Anxiety Disorder 2-item (GAD-2)**") %>%
  bold_labels() %>% 
  as_gt() %>%
  gt::tab_source_note(gt::md("*Source: US Census Bureau, Household Pulse Survey, Week 27*"))

# Patient Health Questionnaire-2 (PHQ-2)
hps.tab2 <- survey::svydesign(ids = ~1, weights = ~pweight, data = hps, strata = NULL) %>%
  tbl_svysummary(by = "phq2", 
                 include = c(gender, education, marital, race_eth2, work.loss, metro, ageg, state, phq2), 
                 percent = "column",
                 label = list(metro ~ "Metropolitan area",
                              state ~ "State",
                              ageg ~ "Age group",
                              gender ~ "Gender",
                              marital ~ "Marital status",
                              education ~ "Educational level",
                              race_eth2 ~ "Race and ethnicity")) %>% 
  add_n() %>% 
  add_p() %>% 
  add_overall() %>% 
  modify_header(label ~ "**Variable**") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**PHQ-2**") %>%
  modify_caption("**Patient Health Questionnaire-2 (PHQ-2)**") %>%
  bold_labels() %>% 
  as_gt() %>%
  gt::tab_source_note(gt::md("*Source: US Census Bureau, Household Pulse Survey, Week 27*"))
```





